### ISSUE TITLE
Wrapper Doesn't create the folder Mac M1

### ISSUE THREAD

**Issue by nunordm** [Gcenx/WineskinServer#96]
- OS: macOS 11.3 (tried on normal and also beta)
 - Winery version: Wineskin-Winery-1.8.4
 - Master Wrapper version: Wineskin-2.9.0.7-rc4
 - Engine version: WS11WineCX64Bit 20.0.2
 - Hardware: [Mac mini M1]
 
![Captura de ecrã 2021-03-23, às 17 11 37](https://user-images.githubusercontent.com/77023843/112188568-ff862b80-8bfa-11eb-9904-29ff4da1b058.png)

I installed Wine Inside the user/Applications/.

![Captura de ecrã 2021-03-23, às 17 12 09](https://user-images.githubusercontent.com/77023843/112188530-f72df080-8bfa-11eb-9582-3db416e9bf84.png)

When I open Wine and press "Create New Blank Wrapper" it asks for the folder name I want.
(Then in the first try it also installed Gecko 2.47.1x86).
It proceeds until I get the Success message with the folder path and also the option to find it on Finder but the "View wrapper in Finder" leads me back to Winery and the "path" doesn't exist, the Wrapper doesn't get created as it says.

![Captura de ecrã 2021-03-23, às 16 09 37](https://user-images.githubusercontent.com/77023843/112187549-1aa46b80-8bfa-11eb-981b-7d96e3549fd2.png)

I've tried reinstalling it, I've tried with SIP disable, in no moment it asked me for permissions but I've found that there's an option to let Wineskin "access to all disk" I've also tried with that but nothing once more.

**Comment by Gcenx** [comment]
When you downloaded Winery did you remove the quarantine flag?, if you didn’t everything it’s downloaded/created will now also contain that flag.

When an app is marked as quarantined it can exhibit strange behavior.

The only other thing would be do you have third party security software installed?, some of those won’t even complain but outright block the action(s), these are usually the Endpoint suites.

**Comment by nunordm** [comment]
When I download I didn't do anything, just when I tried to install it said it wasn't trusted so I couldn't install. I had to go System Preferences / Security and Privacy and then there allow it to "install anyway".
So I am not sure if it is flagged as quarantine or not, is there a way for me to check if it is? Or should I just reinstall without that flag? How so? Sorry about the questions.

About third party security I only have AdGuard for ads on safari so I doubt it is it.

**Comment by Gcenx** [comment]
Remove Wineskin Winery, and remove ~/Library/Application Support/Wineskin

Then install using the listed brew command to install and avoid the quarantine problem.

Also might want to reboot to clear /tmp wouldn’t hurt, then install the master wrapper/engine and making a brew wrapper using a unique name.

**Comment by nunordm** [comment]
I deleted all of that and installed with HomeBrew and still the same problem.
The wrapper doesn't get created even tho it shows as successful, it just goes back to the Wineskin Winery.

https://user-images.githubusercontent.com/77023843/112205322-960f1880-8c0c-11eb-86b9-6be72ed6315d.MOV

Do you think it may be because of macOS beta? Or full disk access permission?

**Comment by Gcenx** [comment]
I know the 11.3 beta had issues for wine64 until Beta3, after this I’ve not been informed of any additional problems.

I’m still running 11.2.3 and won’t be installing another Beta release, but something is definitely off here.

Did the Newley create wrapper even end up in ~/Applications/Wineskin/

**Comment by nunordm** [comment]
Installing via Homebrew the Wineskin Winery gets installed on the normal Applications folder where all apps lay.
In ~/Applications/Wineskin there is nothing created, not even that folder "Wineskin", I think the process of creating a "blank wrapper" just doesn't do anything.

I have the app Wineskin
![Captura de ecrã 2021-03-23, às 19 56 57](https://user-images.githubusercontent.com/77023843/112209920-f18fd500-8c11-11eb-8508-e596a8fec9b2.png)


 I have the Application Support files
![Captura de ecrã 2021-03-23, às 19 56 11](https://user-images.githubusercontent.com/77023843/112209932-f5bbf280-8c11-11eb-90ef-2801d7a618ee.png)

 
But nothing else is created
![Captura de ecrã 2021-03-23, às 19 55 49](https://user-images.githubusercontent.com/77023843/112209978-040a0e80-8c12-11eb-8530-157c6d76cbea.png)


I may try it under normal version not the Beta and/or giving full access to the disk but not sure if this is it.
Anyway thanks for the incredible fast reply!

**Comment by Gcenx** [comment]
You did wipe the Applications support directory for Wineskin right?, then newly downloaded the needed packages?

What’s strange is your the only person having this issue, the only other weirdness due to 11.3 beta was #86 caused issues for wine64 but this only really affected 11.3 Beta 1 & 2 and was resolved in Beta3 along with the Controller API fix.

Maybe you could test if your able to use a wine package outside of Wineskin, 
```
brew install --no-quarantine wine-crossover
```
That’s a build of WineCX19.0.2 that’s close to the provided Engine, then directly call wine winecfg from terminal should get some output.

**Comment by nunordm** [comment]
Yes I wiped the Applications Support and the App itself, it was a fresh install with Homebrew, it had to redownload the Engine and the Wrapper so I know it was all cleared.

I've tried that `Maybe you could test if your able to use a wine package outside of Wineskin,

brew install --no-quarantine wine-crossover
That’s a build of WineCX19.0.2 that’s close to the provided Engine, then directly call wine winecfg from terminal should get some output.`

This is the outcome, it doesn't work but that was probably on me, maybe there is some steps missing, but altleast it is a new Window.

![Captura de ecrã 2021-03-23, às 23 19 24](https://user-images.githubusercontent.com/77023843/112231461-aafca380-8c2e-11eb-9144-e8b62c98ce71.png)

**Comment by Gcenx** [comment]
So the problem for Wineskin on your end might be something with permissions, when the ~/Applications/Wineskin directory is missing it should have created it for you.

Maybe creating that directory manually would resolve your issue?

WineCX19 doesn’t contain all the needed hacks that WineCX20 does but at least it somewhat functioned, WoW can be a PITA at the best of times.

I’d usually say grab PortingKit (it still uses the master wrapper and engines from here) but someone said the most recent version failed to find the master wrapper..., so awaiting on a fix for that.

**Comment by nunordm** [comment]
I can't believe this, creating that folder manually did solve the issue of the Wrapper not being created!
I still get the same WOW error but at least now the Wrapper is created and I can add my .exe to it.
Maybe just something I need to change in Config Utility or Winetricks?

**Comment by Gcenx** [comment]
That’s good to hear creating the directory manually gotten things working for you, guess I’ll need to check why that wasn’t being created automatically like it should be.

As for WoW it’s been a while since I last attempted to play WoW Wotlk, but as the M1 had some annoying bugs maybe try forcing the game into windowed mode.

WineCX20.0.2 and lower can’t use fullscreen at lower resolutions, the unpublished WineCX20.0.4 can but as that requires an entirely new runtime so I can’t provided that currently.

As this only affects older titles with lower resolutions not really in a rush to resolve this as other dependencies still need to be bumped to something recent and Macports-ports is taking forever I’m just doing it myself slowly.

**Comment by nunordm** [comment]
Dude are you kidding? Even tho I still haven't got this working you were amazing!!
Thanks for all the help and fast reply, I understand this is not the most requested feature or need right now so I guess I'll be waiting... M1 is incredible fast and cool but it sure did bring some new issues ahah.
I'll be honest, right now I can't afford to donate and sorry about that but as soon as I can I'll be doing so! You sure deserve it for all the help and support.

**Comment by Haibo-Zhou** [comment]
> I can't believe this, creating that folder manually did solve the issue of the Wrapper not being created!
> I still get the same WOW error but at least now the Wrapper is created and I can add my .exe to it.
> Maybe just something I need to change in Config Utility or Winetricks?

Man, you are not alone. I'm using Mac mini M1 11.2.1 and got the exactly same issue with you.

**Comment by Gcenx** [comment]
@Haibo-Zhou how did you install Winery exactly, as I’d never gotten this issue when I’d first purchased the M1 Mac mini (paid for with donations from members here)

I downloaded the current “pre release” version of Winery then removed the quarantine flag before extracting the archive.

Installing via `brew` using the provided command also installs Winery without quarantine flags being added.

**Comment by Haibo-Zhou** [comment]
@Gcenx well, I download it from your github page and specific from the manually link "Download Wineskin Winery v1.8.4.2", then update the wrapper and install the engine online. And yeah, I remove the quarantine flag too, otherwise Mac says that the app is damaged.

And since I could have the blank wrapper created now, I'm going to see how to install the exe game now:)

**Comment by Gcenx** [comment]
@Haibo-Zhou so you also confirm manually creating the directory gotten Winery working for you?

As the next master wrapper (Wineskin-2.9.0.8) was pushed I can look into this and make any bug fixes/updates to a Winery.

**Comment by Haibo-Zhou** [comment]
Yes, manually creating the Wineskin folder in ~/applications works.

**Comment by Gcenx** [comment]
Pinning the issue until I’ve resolved it properly within Winery.

**Comment by Gcenx** [comment]
Until I’ve had chance to work on Winery I’ve modified the brew formula to create the needed directory.

**Comment by Faelixx** [comment]
> Yes, manually creating the Wineskin folder in ~/applications works.

This was not the resolution for my problem! 

I found this thread because I too was having the same issue of a missing wineskin folder in my Applications folder. 

After countless efforts of trying to make it work, I was going through my cache etc.. deleting unnecessary folders/files and what do you know, the wrappers I was creating were being placed in the hidden tmp folder. 

After creating the wrapper and dragging/dropping it out of my tmp folder I was able to use the wrapper and my windows program with no issue. 

I don't know if it was a glitch on my end, but it seems like the Wineskin Winery.app was creating the wrappers in a different location then the location shown after it had been created. 

I hope this helps anyone who is in need!
